### ISSUE TITLE
icon for .txt files is not showing up

### ISSUE THREAD

**Issue by ilias-sp** [websemantics/file-icons#1]
hi and thanks for your library!

i noticed that when using your library, the .txt files are not getting their file icon displayed. i believe it has to do with the mapping you used "icon-file-text" in icondb.php, which doesnt exist in the css.

what i did to overcome the issue is replace in that file the "icon-file-text" with "text-icon" which does exist in the css file.

if you are interested for a pull request to fix that, plz let me know and will do it.

thanks

**Comment by websemantics** [comment]
Sorry for not replying earlier, I'll close this but please feel free to send a pull request.
Thanks @ilias-sp
